### PR TITLE
Throws javascript error in dossieroverview in IE10.

### LINKED ISSUE #45: BUG: Javascript error if no index is defined in IE10
Zeile: 336
Zeichen: 17
Fehlermeldung: Unable to get property 'id' of undefined or null reference

### PR DESCRIPTION
**Pull request by bierik**
Fixes #45 

When no index is defined set to 0 to display the first tab.

### CODE REVIEW

**Comment by phgross** [comment]
@bierik changelog entry is missing, otherwise :+1:  

@maethu any objections?

**Comment by bierik** [comment]
@phgross updated

**Comment by maethu** [comment]
nope

**Comment by maethu** [comment]
@phgross haha :smile:

**Pull request merged**
